---

- hosts: all
  become: true
  pre_tasks: 

    #    - name: update DNF cache
    # tags: always
    # dnf:
    #   update_cache: yes
    # changed_when: false

    - name: install update
      tags: always
      dnf:
        name: '*'
        state: latest

- name: Setting up Host Servers
  hosts: host_servers
  become: yes
  roles: 
    - host_servers

- name: Run corosync and Pacemaker on host servers
  hosts: highavailability
  become: yes
  roles:
    - corosync-pacemaker

- name: Install ZFS
  hosts: shared_storage
  become: yes
  roles: 
    - shared-storage
