---

- hosts: all
  become: true
  pre_tasks: 

    - name: update DNF cache
      tags: always
      dnf:
        update_cache: yes
      changed_when: false

    - name: install update
      tags: always
      dnf:
        name: '*'
        state: latest

- name: Install and configure KVM with Bridge on server1 & server2
  hosts: server1:server2
  become: true
  tasks:

    - name: install KVM and related package
      tags: kvm,libvirtd,qemu
      dnf: 
        name:
          - qemu-kvm
          - libvirt
          - virt-install
          - bridge-utils
          - virt-manager
          - virt-viewer
        state: present

    - name: Enable and start libvirtd service
      tags: kvm,libvirtd,qemu
      systemd:
        name: libvirtd
        state: started
        enabled: yes 

- name: Run corosync and Pacemaker on host servers
  hosts: host_servers
  roles:
    - corosync-pacemaker

