---

- name: Check if VM already exists
  command: "virsh list --all | grep {{ vm_name }}"
  register: vm_exists
  failed_when: false
  changed_when: false

- name: Check if VM disk image is associated with specified VM
  command: "virsh domblklist --domain {{ vm_name }}"
  register: disk_association_specific
  failed_when: false
  changed_when: false

- name: Check if VM disk image is associated with any VM
  command: "virsh domblklist --all | grep {{ disk_path }}"
  register: disk_association_general
  failed_when: false
  changed_when: false

- name: Create VM
  command: >
    virt-install --name {{ vm_name }} --ram {{ memory }} --vcpus {{ vcpus }}
    --disk path={{ disk_path }} --cdrom {{ iso_path }}
    --network bridge={{ network }} --graphics vnc,listen=0.0.0.0
    --os-variant generic --noautoconsole
  when: vm_exists.rc != 0 and disk_association_specific.rc != 0 and disk_association_general.rc != 0
