# /roles/vm-creation/vm-img/tasks/main.yml

---

- name: Check if VM disk image exists
  stat:
    path: "{{ disk_path }}"
  register: disk_image

- name: Create VM disk image
  command: "qemu-img create -f qcow2 {{ disk_path }} 20G"
  when: not disk_image.stat.exists

