# /roles/vm-creation/vm-iso/tasks/main.yml

---

- name: Check if ISO exists
  stat:
    path: "{{ iso_path }}"
  register: os_iso

- name: Download OS ISO
  get_url:
    url: "{{ iso_url }}"
    dest: "{{ iso_path }}"
    mode: '0755'
  when: not os_iso.stat.exists
