---

- name: Install necessary package
  dnf:
    name:
      - pacemaker-2.1.6-9.el9.x86_64
      - corosync-3.1.7-1.el9.x86_64
      - pcs-0.11.6-3.el9.x86_64
      - fence-agents-all-4.10.0-55.el9.x86_64
    state: present
    enablerepo: highavailability
  become: yes
  
- name: start and enable pcsd service
  service:
    name: pcsd
    state: started
    enabled: yes
  become: yes

- name: Add firewall rules for cluster communication
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 2224/tcp
    - 3121/tcp
    - 21064/tcp
  become: yes

- name: Reload firewalld
  command:
    cmd: firewall-cmd --reload
  become: yes


- name: Setup authentication for pcsd
  command:
    cmd: "echo {{ pcsd_password }} | pcs host auth {{ cluster_nodes }} -u hacluster"
  become: yes
  vars:
    pcsd_password: ntserverp
    cluster_nodes:
      - 192.168.88.125
      - 192.168.88.126
      - 192.168.88.112
      - 192.168.88.113
      - 192.168.88.114
      - 192.168.88.115

- name: Ensure corosync user exists
  user:
    name: corosync
    system: yes
  become: yes
     
- name: Copy Corosync configuration
  copy:
    src: corosync.conf
    dest: /etc/corosync/corosync.conf
  become: yes
 
- name: Start and Enable Corosync and Pacemaker
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - corosync
    - pacemaker

- name: Check if cluster is already set up
  command: pcs status xml
  register: cluster_status
  failed_when: false
  changed_when: false
  become: yes

- name: Setup cluster
  command:
    cmd: "pcs cluster setup cluster1 {{ cluster_nodes | join(' ') }}"
  when: inventory_hostname == "192.168.88.125"
  become: yes

- name: Start cluster
  command:
    cmd: "pcs cluster start --all"
  become: yes
 
- name: Enable cluster at boot
  command:
    cmd: "pcs cluster enable --all"
  become: yes

