---

- name: Install packages for CentOS Stream 8
  dnf: 
    name:
      - pacemaker
      - corosync
      - pcs
      - clufter-lib-pcs
      - fence-agents-all
    enablerepo: ha 
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'

- name: Install packages for Rocky Linux
  dnf:
    name:
      - pacemaker
      - corosync
      - pcs
      - fence-agents-all
    state: present
  when: ansible_distribution == 'Rocky' and ansible_distribution_major_version == '9'


- name: start and enable pcsd service
  service:
    name: pcsd
    state: started
    enabled: yes
  become: yes
  changed_when: false

- name: Add firewall rules for cluster communication
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 2224/tcp
    - 3121/tcp
    - 21064/tcp
  become: yes

- name: Reload firewalld
  command:
    cmd: firewall-cmd --reload
  become: yes
  changed_when: false


- name: Ensure corosync user exists
  user:
    name: corosync
    system: yes
  become: yes
  changed_when: false
     
- name: Start and Enable Corosync and Pacemaker
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - corosync
    - pacemaker
  changed_when: false

- name: Check if cluster is already set up
  command: pcs status xml
  register: cluster_status
  failed_when: false
  changed_when: false
  become: yes

- name: Enable cluster at boot
  command:
    cmd: "pcs cluster enable --all"
  become: yes
  changed_when: false

- name: Print PCS Status for cluster1 and cluster2
  command: 
    cmd: pcs status
  delegate_to: "{{ item }}"
  with_items:
    - 192.168.88.125
    - 192.168.88.112
  become: yes
  changed_when: false
